# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import modelcluster.fields
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20150323_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPanelPageDocument',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sort_order', models.IntegerField(null=True, editable=False, blank=True)),
                ('doc', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, blank=True, to='core.DocumentPage', null=True)),
                ('page', modelcluster.fields.ParentalKey(related_name='documents', to='core.ForumPanelPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ForumPanelPagePhotoAlbum',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sort_order', models.IntegerField(null=True, editable=False, blank=True)),
                ('album', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, blank=True, to='core.PhotoAlbumPage', null=True)),
                ('page', modelcluster.fields.ParentalKey(related_name='albums', to='core.ForumPanelPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ForumPanelPageVideo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sort_order', models.IntegerField(null=True, editable=False, blank=True)),
                ('page', modelcluster.fields.ParentalKey(related_name='videos', to='core.ForumPanelPage')),
                ('video', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, blank=True, to='core.VideoPage', null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.RemoveField(
            model_name='forumpagedocumenten',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='forumpagedocumenten',
            name='page',
        ),
        migrations.DeleteModel(
            name='ForumPageDocumentEN',
        ),
        migrations.RemoveField(
            model_name='forumpagedocumentru',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='forumpagedocumentru',
            name='page',
        ),
        migrations.DeleteModel(
            name='ForumPageDocumentRU',
        ),
        migrations.RemoveField(
            model_name='forumpagephotoalbumen',
            name='album',
        ),
        migrations.RemoveField(
            model_name='forumpagephotoalbumen',
            name='page',
        ),
        migrations.DeleteModel(
            name='ForumPagePhotoAlbumEN',
        ),
        migrations.RemoveField(
            model_name='forumpagephotoalbumru',
            name='album',
        ),
        migrations.RemoveField(
            model_name='forumpagephotoalbumru',
            name='page',
        ),
        migrations.DeleteModel(
            name='ForumPagePhotoAlbumRU',
        ),
        migrations.RemoveField(
            model_name='forumpagetimetableday',
            name='page',
        ),
        migrations.DeleteModel(
            name='ForumPageTimetableDay',
        ),
        migrations.RemoveField(
            model_name='forumpagevideoen',
            name='page',
        ),
        migrations.RemoveField(
            model_name='forumpagevideoen',
            name='video',
        ),
        migrations.DeleteModel(
            name='ForumPageVideoEN',
        ),
        migrations.RemoveField(
            model_name='forumpagevideoru',
            name='page',
        ),
        migrations.RemoveField(
            model_name='forumpagevideoru',
            name='video',
        ),
        migrations.DeleteModel(
            name='ForumPageVideoRU',
        ),
        migrations.DeleteModel(
            name='ForumTimetableItem',
        ),
        migrations.RemoveField(
            model_name='forumtimetablepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ForumTimetablePage',
        ),
        migrations.RemoveField(
            model_name='homepagematerialvideoen',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagematerialvideoen',
            name='video',
        ),
        migrations.DeleteModel(
            name='HomePageMaterialVideoEN',
        ),
        migrations.RemoveField(
            model_name='homepagematerialvideoru',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagematerialvideoru',
            name='video',
        ),
        migrations.DeleteModel(
            name='HomePageMaterialVideoRU',
        ),
        migrations.RemoveField(
            model_name='allspeakersindexpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='allspeakersindexpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='documentpage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='documentpage',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='documentpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='documentpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='documentpage',
            name='is_browsable',
        ),
        migrations.RemoveField(
            model_name='documentpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='documentpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='forumindexpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='forumindexpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='forumlocationpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='forumlocationpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='forumpackagespage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='forumpackagespage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='forumpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='forumpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='forumpanelpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='forumpanelpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='forumregistrationpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='forumregistrationpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='forumspeakerspage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='forumspeakerspage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='materialsalbumspage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='materialsalbumspage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='materialsdocumentspage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='materialsdocumentspage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='materialspage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='materialspage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='materialsvideopage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='materialsvideopage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='organizerpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='organizerpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='orgpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='orgpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='participationpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='participationpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='partnerlistpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='partnerlistpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='photoalbumpage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='photoalbumpage',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='photoalbumpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='photoalbumpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='photoalbumpage',
            name='is_browsable',
        ),
        migrations.RemoveField(
            model_name='photoalbumpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='photoalbumpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='presstoplistpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='presstoplistpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='presstoppage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='presstoppage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='presstoppage',
            name='is_browsable',
        ),
        migrations.RemoveField(
            model_name='presstoppage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='presstoppage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='programpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='programpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='programsectionpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='programsectionpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='radapage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='radapage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='speakerpage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='speakerpage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='has_en',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='has_ru',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='is_browsable',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='documentpage',
            name='language',
            field=models.CharField(default=b'uk', max_length=2, choices=[(b'uk', 'Ukrainian'), (b'ru', 'Russian'), (b'en', 'English')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photoalbumpage',
            name='language',
            field=models.CharField(default=b'uk', max_length=2, choices=[(b'uk', 'Ukrainian'), (b'ru', 'Russian'), (b'en', 'English')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='presstoppage',
            name='language',
            field=models.CharField(default=b'uk', max_length=2, choices=[(b'uk', 'Ukrainian'), (b'ru', 'Russian'), (b'en', 'English')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='videopage',
            name='language',
            field=models.CharField(default=b'uk', max_length=2, choices=[(b'uk', 'Ukrainian'), (b'ru', 'Russian'), (b'en', 'English')]),
            preserve_default=True,
        ),
    ]
